// ─────────────────────────────────────────────────────────────────────────────
// lib/cloudflareStream.ts
// Cloudflare Stream URL helpers — video's equivalent of lib/cloudflareImages.ts.
// Videos are uploaded with `downloadable: true` (see the migration script),
// which gives a direct, single MP4 file instead of an HLS manifest. That's a
// deliberate choice for this site's two use cases (an autoplay muted loop, a
// simple modal player) — neither needs adaptive bitrate streaming, and a
// direct MP4 is lighter (no manifest round-trip, no HLS.js) and drops
// straight into the existing plain <video> tags unchanged.
// Set NEXT_PUBLIC_CLOUDFLARE_STREAM_CODE in .env.local (the "customer
// subdomain code" shown in the migration script's output / Stream dashboard).
// ─────────────────────────────────────────────────────────────────────────────

const STREAM_CODE = process.env.NEXT_PUBLIC_CLOUDFLARE_STREAM_CODE
const BASE = `https://customer-${STREAM_CODE}.cloudflarestream.com`

// Direct MP4 — requires the video to have been uploaded with downloads
// enabled (see scripts/migrate-video-to-cloudflare-stream.ts).
export const cfVideo = (uid: string) => `${BASE}/${uid}/downloads/default.mp4`

// Poster/thumbnail frame — auto-generated by Stream, no extra step needed.
export const cfVideoPoster = (uid: string) => `${BASE}/${uid}/thumbnails/thumbnail.jpg`
